# Generated by Django 5.2 on 2025-05-06 09:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('policy', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=10, null=True)),
                ('member_relation', models.CharField(blank=True, choices=[('E', 'Self-E'), ('S', 'Spouse-S'), ('D', 'Daughter-D'), ('C', 'Son-C')], max_length=10, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits.', regex='^\\d{12}$')])),
                ('pan_no', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('health_condition', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30)),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_type', models.CharField(blank=True, choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], max_length=10, null=True)),
                ('coverage_amount1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_amount1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_premium_amount1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_policies', to='agents.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to='customer.customer')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to='policy.plan')),
                ('plan_coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to='policy.plancoverage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to='policy.policy')),
            ],
        ),
        migrations.CreateModel(
            name='AgentIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='agents.agent')),
                ('customer_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='customer.customerpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=100)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('address3', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('E', 'Self-E'), ('S', 'Spouse-S'), ('D', 'Daughter-D'), ('C', 'Son-C')], max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.TextField()),
                ('pincode', models.TextField()),
                ('pan_no', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('brother', 'Brother')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('nominee_appointee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='customer.customer')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='customer.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('other', 'Other')], max_length=20)),
                ('payment_status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('loan_tenure', models.IntegerField(blank=True, null=True)),
                ('good_health_declaration', models.BooleanField(blank=True, default=False, null=True)),
                ('GHI_sum_insured', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GPA_sum_insured', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GCC_sum_insured', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EMI_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SI_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('SI_date', models.DateField(blank=True, null=True)),
                ('total_premium_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customer')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policy.policy')),
            ],
        ),
        migrations.CreateModel(
            name='UserIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('customer_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='users.user')),
            ],
        ),
    ]
