# Generated by Django 4.2.18 on 2025-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Branch Manager', 'Branch Manager')], max_length=50)),
            ],
        ),
    ]
