# Generated by Django 5.2 on 2025-05-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_amount', models.TextField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='policy.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverage_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=10, null=True)),
                ('commission_agent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_kannat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_term_duration', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('grace_period', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('late_payment_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maturity_benefits', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('terms_conditions_document', models.FileField(blank=True, null=True, upload_to='policy_documents/')),
                ('policy_brochure', models.FileField(blank=True, null=True, upload_to='policy_documents/')),
                ('no_claim_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('policy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policycategory')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='policy.policy'),
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.company')),
                ('policy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policycategory')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policytype'),
        ),
    ]
